*&---------------------------------------------------------------------*
*&  Include           /MBTOOLS/MBT_TEMPLATE_4_INIT
*&---------------------------------------------------------------------*

INITIALIZATION.

* Setup
  TRY.
      zcl_abapinst_setup=>run(
        iv_tabname = c_tabname
        iv_lock    = c_lock
        iv_text    = |Generated by { c_title }| ).

      zcl_abapinst_installer=>init(
        iv_tabname = c_tabname
        iv_lock    = c_lock
        iv_name    = 'Marc Bernard Tool'
        iv_names   = 'Marc Bernard Tools' ).
    CATCH zcx_abapinst_exception INTO gx_error.
      MESSAGE gx_error TYPE 'E' DISPLAY LIKE 'I'.
      STOP.
  ENDTRY.

* Textpool
  CREATE OBJECT go_textpool EXPORTING iv_program = sy-cprog.

  go_textpool->set( 'R,,' && c_title ).
  go_textpool->set( 'S,P_CONN_O,Internet Server' ).
  go_textpool->set( 'S,P_CONN_P,Password' ).
  go_textpool->set( 'S,P_CONN_U,User' ).
  go_textpool->set( 'S,P_FILE_F,Your Computer' ).
  go_textpool->set( 'S,P_FILE_I,Internet' ).
  go_textpool->set( 'S,P_FILE_S,Application Server' ).
  go_textpool->set( 'S,P_FOLD_D,Default (from abapGit Package)' ).
  go_textpool->set( 'S,P_FOLD_F,Full' ).
  go_textpool->set( 'S,P_FOLD_P,Prefix' ).
  go_textpool->set( 'S,P_LAYR_T,Transport Layer' ).
  go_textpool->set( 'S,P_PACK_L,Local Package' ).
  go_textpool->set( 'S,P_PACK_T,Transportable Package' ).
  go_textpool->set( 'S,P_PROX_H,Host' ).
  go_textpool->set( 'S,P_PROX_O,Internet Proxy' ).
  go_textpool->set( 'S,P_PROX_P,Password' ).
  go_textpool->set( 'S,P_PROX_S,Port' ).
  go_textpool->set( 'S,P_PROX_U,User' ).
  go_textpool->set( 'S,P_REQ_E,Transport Request' ).
  go_textpool->set( 'S,P_SAP_D,Default (from abapGit Package)' ).
  go_textpool->set( 'S,P_SAP_L,Local Package' ).
  go_textpool->set( 'S,P_SAP_T,Transportable Package' ).
  go_textpool->set( 'S,P_SOFT_T,Software Component' ).
  go_textpool->set( 'S,P_TSP_E,Use Existing Transport' ).
  go_textpool->set( 'S,P_TSP_N,Create New Transport' ).
  go_textpool->set( 'S,P_ZIP_F,Local File' ).
  go_textpool->set( 'S,P_ZIP_I,Internet' ).
  go_textpool->set( 'S,P_ZIP_S,Application Server' ).

  go_textpool->save( ).

*-----------------------------------------------------------------------

* Function Keys
  sscrfields-functxt_01 = icon_expand && 'Show Options'.
  sscrfields-functxt_02 = icon_install_package && 'List Packages'.
  sscrfields-functxt_03 = icon_delete && 'Uninstall Package'.

* Header
  scr_t001 = 'An Installer for Marc Bernard Tools'.

*-----------------------------------------------------------------------

* Source Tab
  scr_tab1 = zcl_abapinst_screen=>header( iv_icon = icon_install_package
                                          iv_text = 'MBT Package' ).

  scr_t100 =
  'Select the source of your MBT installation package.'.
  scr_t101 =
  'The package must be a zip file that contains code and objects of the tool.'.

  scr_t102 = 'URL'.
  scr_t103 = 'File name'.
  scr_t104 = 'File name (EPS Inbox)'.

*-----------------------------------------------------------------------

* Authentication Tab
  scr_tab4 = zcl_abapinst_screen=>header( iv_icon = icon_connect
                                          iv_text = 'Authentication' ).

  scr_t400 =
  'When downloading the MBT package from the Internet, you might have to'.
  scr_t401 =
  'authenticate yourself at the server and/or your proxy.'.

  scr_t402 = 'User'.
  scr_t403 = 'Password'.
  scr_t404 = 'Proxy Host'.
  scr_t405 = 'Proxy Port'.
  scr_t406 = 'Proxy User'.
  scr_t407 = 'Proxy Password'.

*-----------------------------------------------------------------------

* Target Tab
  scr_tab2 = zcl_abapinst_screen=>header( iv_icon = icon_package_standard
                                          iv_text = 'SAP Package' ).

  scr_t200 =
  'Select the target SAP package for your installation.'.
  scr_t201 =
  'If the package does not exist, it will be created automatically.'.

*-----------------------------------------------------------------------

* Transport Tab
  scr_tab3 = zcl_abapinst_screen=>header( iv_icon = icon_transport
                                          iv_text = 'Transport' ).

  scr_t300 =
  'When installing into a transportable package, decide if you want to create'.
  scr_t301 =
  'a new transport request or select an existing one.'.

*-----------------------------------------------------------------------

* Options Tab
  scr_tab8 = zcl_abapinst_screen=>header( iv_icon = icon_icon_list
                                          iv_text = 'Options' ).

  scr_t800 =
  'You can select the folder logic to be used and whether you want only'.
  scr_t801 =
  'the main language of the package to be installed.'.

  scr_t810 = 'Folder Logic:'.

*-----------------------------------------------------------------------

* About Tab
  scr_tab9 = zcl_abapinst_screen=>header( iv_icon = icon_system_help
                                          iv_text = 'About' ).

  scr_t900 = |Copyright © { sy-datum(4) } Marc Bernard Tools. All right reserved.|.
  scr_t901 = 'An Installer for Marc Bernard Tools'.
  scr_t902 = |Version { zif_abapinst_definitions=>gc_version }|.

  b_docu = zcl_abapinst_screen=>icon( iv_name = icon_system_extended_help
                                      iv_text = 'Documentation'
                                      iv_info = '' ).
  b_lice = zcl_abapinst_screen=>icon( iv_name = icon_legal_reg
                                      iv_text = 'License'
                                      iv_info = '' ).
  b_repo = zcl_abapinst_screen=>icon( iv_name = icon_url
                                      iv_text = 'Website'
                                      iv_info = '' ).
