*&---------------------------------------------------------------------*
*&  Include           /MBTOOLS/MBT_TEMPLATE_3_SCREEN
*&---------------------------------------------------------------------*

" Function Keys
SELECTION-SCREEN FUNCTION KEY: 1, 2, 3.

*-----------------------------------------------------------------------

" Source Package
SELECTION-SCREEN BEGIN OF SCREEN 100 AS SUBSCREEN.

SELECTION-SCREEN BEGIN OF BLOCK b100 WITH FRAME.
SELECTION-SCREEN COMMENT:
   /1(77) scr_t100,
   /1(77) scr_t101.
SELECTION-SCREEN END OF BLOCK b100.

SELECTION-SCREEN BEGIN OF BLOCK b110 WITH FRAME.

PARAMETERS:
  p_zip_f RADIOBUTTON GROUP g1 DEFAULT 'X' USER-COMMAND c100.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t103 FOR FIELD p_file_f.
PARAMETERS:
  p_file_f TYPE char255 LOWER CASE
    DEFAULT 'C:\*.zip' MODIF ID c12.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 2.
PARAMETERS:
  p_zip_i RADIOBUTTON GROUP g1.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t102 FOR FIELD p_file_i.
PARAMETERS:
  p_file_i TYPE char255 LOWER CASE
    DEFAULT 'https://github.com/*.zip' MODIF ID c11.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 2.
PARAMETERS:
  p_zip_s RADIOBUTTON GROUP g1.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t104 FOR FIELD p_file_s.
PARAMETERS:
  p_file_s TYPE char255 LOWER CASE
    DEFAULT '*.zip' MODIF ID c13.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK b110.

SELECTION-SCREEN END OF SCREEN 100.

*-----------------------------------------------------------------------

" Target Package
SELECTION-SCREEN BEGIN OF SCREEN 200 AS SUBSCREEN.

SELECTION-SCREEN BEGIN OF BLOCK b200 WITH FRAME.
SELECTION-SCREEN COMMENT:
   /1(77) scr_t200,
   /1(77) scr_t201.
SELECTION-SCREEN END OF BLOCK b200.

SELECTION-SCREEN BEGIN OF BLOCK b210 WITH FRAME.

PARAMETERS:
  p_sap_d RADIOBUTTON GROUP g2 DEFAULT 'X' USER-COMMAND c200.

SELECTION-SCREEN SKIP 2.
PARAMETERS:
  p_sap_l RADIOBUTTON GROUP g2.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4.
PARAMETERS:
  p_pack_l TYPE devclass DEFAULT '' MODIF ID c21.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 2.
PARAMETERS:
  p_sap_t RADIOBUTTON GROUP g2.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4.
PARAMETERS:
  p_pack_t TYPE pbpackdata-devclass  DEFAULT '' MODIF ID c22,
  p_soft_t TYPE pbpackdata-dlvunit   DEFAULT '' MODIF ID c22,
  p_layr_t TYPE pbpackdata-pdevclass DEFAULT '' MODIF ID c22.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 2.
SELECTION-SCREEN END OF BLOCK b210.

SELECTION-SCREEN END OF SCREEN 200.

*-----------------------------------------------------------------------

" Transport
SELECTION-SCREEN BEGIN OF SCREEN 300 AS SUBSCREEN.

SELECTION-SCREEN BEGIN OF BLOCK b300 WITH FRAME.
SELECTION-SCREEN COMMENT:
   /1(77) scr_t300,
   /1(77) scr_t301.
SELECTION-SCREEN END OF BLOCK b300.

SELECTION-SCREEN BEGIN OF BLOCK b310 WITH FRAME.

PARAMETERS:
  p_tsp_n RADIOBUTTON GROUP g3 USER-COMMAND c300.

SELECTION-SCREEN SKIP 2.
PARAMETERS:
  p_tsp_e RADIOBUTTON GROUP g3.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4.
PARAMETERS:
  p_req_e TYPE trkorr MODIF ID c31.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN SKIP 6.
SELECTION-SCREEN END OF BLOCK b310.

SELECTION-SCREEN END OF SCREEN 300.

*-----------------------------------------------------------------------

" Authentication
SELECTION-SCREEN BEGIN OF SCREEN 400 AS SUBSCREEN.

SELECTION-SCREEN BEGIN OF BLOCK b400 WITH FRAME.
SELECTION-SCREEN COMMENT:
   /1(77) scr_t400,
   /1(77) scr_t401.
SELECTION-SCREEN END OF BLOCK b400.

SELECTION-SCREEN BEGIN OF BLOCK b410 WITH FRAME.

PARAMETERS:
  p_conn_o AS CHECKBOX USER-COMMAND c400.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t402 FOR FIELD p_conn_u.
PARAMETERS:
  p_conn_u TYPE char255 LOWER CASE MODIF ID c40.
SELECTION-SCREEN: END OF LINE, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t403 FOR FIELD p_conn_p.
PARAMETERS:
  p_conn_p TYPE char255 LOWER CASE MODIF ID p40.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN SKIP 2.

PARAMETERS:
  p_prox_o AS CHECKBOX USER-COMMAND c410.
SELECTION-SCREEN: SKIP, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t404 FOR FIELD p_prox_h.
PARAMETERS:
  p_prox_h TYPE char255 LOWER CASE MODIF ID c41.
SELECTION-SCREEN: END OF LINE, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t405 FOR FIELD p_prox_s.
PARAMETERS:
  p_prox_s TYPE char5 MODIF ID c41.
SELECTION-SCREEN: END OF LINE, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t406 FOR FIELD p_prox_u.
PARAMETERS:
  p_prox_u TYPE char255 LOWER CASE MODIF ID c41.
SELECTION-SCREEN: END OF LINE, BEGIN OF LINE, POSITION 4,
  COMMENT (22) scr_t407 FOR FIELD p_prox_p.
PARAMETERS:
  p_prox_p TYPE char255 LOWER CASE MODIF ID p41.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN END OF BLOCK b410.

SELECTION-SCREEN END OF SCREEN 400.

*-----------------------------------------------------------------------

" Options
SELECTION-SCREEN BEGIN OF SCREEN 800 AS SUBSCREEN.

SELECTION-SCREEN BEGIN OF BLOCK b800 WITH FRAME.
SELECTION-SCREEN COMMENT:
      /1(77) scr_t800,
      /1(77) scr_t801.
SELECTION-SCREEN END OF BLOCK b800.

SELECTION-SCREEN BEGIN OF BLOCK b810 WITH FRAME.

SELECTION-SCREEN COMMENT:
   /1(77) scr_t810.
SELECTION-SCREEN SKIP.
PARAMETERS:
  p_fold_d RADIOBUTTON GROUP g8 DEFAULT 'X'.
SELECTION-SCREEN SKIP.
PARAMETERS:
  p_fold_p RADIOBUTTON GROUP g8.
SELECTION-SCREEN SKIP.
PARAMETERS:
  p_fold_f RADIOBUTTON GROUP g8.

SELECTION-SCREEN SKIP 4.
SELECTION-SCREEN END OF BLOCK b810.

SELECTION-SCREEN END OF SCREEN 800.

*-----------------------------------------------------------------------

" About
SELECTION-SCREEN:
  BEGIN OF SCREEN 900 AS SUBSCREEN,
    BEGIN OF BLOCK b900 WITH FRAME,
      COMMENT /1(77) scr_t900,
      COMMENT /1(50) scr_t901,
      COMMENT 60(25) scr_t902,
    END OF BLOCK b900,
    BEGIN OF BLOCK b910 WITH FRAME,
      PUSHBUTTON /1(55) b_docu USER-COMMAND docu,
      SKIP,
      PUSHBUTTON /1(55) b_lice USER-COMMAND lice,
      SKIP,
      PUSHBUTTON /1(55) b_repo USER-COMMAND repo,
    END OF BLOCK b910,
  END OF SCREEN 900.

*-----------------------------------------------------------------------

" Header
SELECTION-SCREEN:
  BEGIN OF BLOCK scr_header,
    SKIP,
    SKIP,
    COMMENT /3(77) scr_t001 FOR FIELD p_zip_f,
    SKIP,
  END OF BLOCK scr_header,
  BEGIN OF TABBED BLOCK scr_tab FOR 19 LINES,
    TAB (40) scr_tab1 USER-COMMAND scr_push1
      DEFAULT SCREEN 0100 MODIF ID t01,
    TAB (40) scr_tab2 USER-COMMAND scr_push2
      DEFAULT SCREEN 0200 MODIF ID t02,
    TAB (40) scr_tab3 USER-COMMAND scr_push3
      DEFAULT SCREEN 0300 MODIF ID t03,
    TAB (40) scr_tab4 USER-COMMAND scr_push4
      DEFAULT SCREEN 0400 MODIF ID t04,
    TAB (40) scr_tab8 USER-COMMAND scr_push8
      DEFAULT SCREEN 0800 MODIF ID t08,
    TAB (40) scr_tab9 USER-COMMAND scr_push9
      DEFAULT SCREEN 0900,
  END OF BLOCK scr_tab.
